// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQdHMis7AH0nYZrVOmn2EBxagZeowWqlI',
    appId: '1:1081481250045:web:71a925f99c95d2c1d1aa94',
    messagingSenderId: '1081481250045',
    projectId: 'ig-clone-pepsidev',
    authDomain: 'ig-clone-pepsidev.firebaseapp.com',
    storageBucket: 'ig-clone-pepsidev.firebasestorage.app',
    measurementId: 'G-X4HQZ1NZ30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpgNjBszhDE42G5eKqMAKUaAyr25y76lA',
    appId: '1:1081481250045:android:f0872cb7d457eaeed1aa94',
    messagingSenderId: '1081481250045',
    projectId: 'ig-clone-pepsidev',
    storageBucket: 'ig-clone-pepsidev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIRq9ROOhmBNG93oV95-886Q5vFAlfU_c',
    appId: '1:1081481250045:ios:a28d6553862d5063d1aa94',
    messagingSenderId: '1081481250045',
    projectId: 'ig-clone-pepsidev',
    storageBucket: 'ig-clone-pepsidev.firebasestorage.app',
    iosBundleId: 'com.example.appFlutterStarterForJob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIRq9ROOhmBNG93oV95-886Q5vFAlfU_c',
    appId: '1:1081481250045:ios:a28d6553862d5063d1aa94',
    messagingSenderId: '1081481250045',
    projectId: 'ig-clone-pepsidev',
    storageBucket: 'ig-clone-pepsidev.firebasestorage.app',
    iosBundleId: 'com.example.appFlutterStarterForJob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQdHMis7AH0nYZrVOmn2EBxagZeowWqlI',
    appId: '1:1081481250045:web:790cfffbeaafab5cd1aa94',
    messagingSenderId: '1081481250045',
    projectId: 'ig-clone-pepsidev',
    authDomain: 'ig-clone-pepsidev.firebaseapp.com',
    storageBucket: 'ig-clone-pepsidev.firebasestorage.app',
    measurementId: 'G-WRFKV4EGGP',
  );
}
